import { F, FM } from "./constants";

export const S = {
  app: { fontFamily: F, background: "#f5f7fb", color: "#172033", minHeight: "100vh", display: "flex", flexDirection: "column" },
  loginPage: { fontFamily: F, background: "#eef4ff", color: "#172033", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  loginCard: { width: "100%", maxWidth: 430, background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: 26, boxShadow: "0 20px 55px rgba(15, 23, 42, 0.12)" },
  loginMark: { display: "inline-flex", color: "#2563eb", fontSize: 22, marginBottom: 8 },
  loginTitle: { fontSize: 24, color: "#172033", margin: "0 0 6px", lineHeight: 1 },
  errorText: { color: "#f87171", fontSize: 12, margin: "0 0 8px" },
  loading: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100vh", background: "#f5f7fb" },
  spinner: { width: 28, height: 28, border: "3px solid #dbe5f0", borderTop: "3px solid #2563eb", borderRadius: "50%", animation: "spin 0.7s linear infinite" },
  nav: { background: "#ffffff", borderBottom: "1px solid #dbe5f0", padding: "14px 20px 0", position: "sticky", top: 0, zIndex: 50, boxShadow: "0 1px 10px rgba(15, 23, 42, 0.04)" },
  navTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, flexWrap: "wrap", gap: 8 },
  brand: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  brandTitle: { fontSize: 15, fontWeight: 800, color: "#172033" },
  navActions: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
  tabs: { display: "flex", gap: 0, overflowX: "auto" },
  bRed: { fontSize: 10, padding: "3px 8px", borderRadius: 999, background: "#fee2e2", color: "#b91c1c", fontWeight: 700 },
  bAmber: { fontSize: 10, padding: "3px 8px", borderRadius: 999, background: "#fef3c7", color: "#92400e", fontWeight: 700 },
  searchBox: { background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 6, color: "#172033", padding: "8px 12px", fontSize: 12, fontFamily: F, width: 260, outline: "none" },
  addBtn: { background: "#2563eb", color: "#fff", border: "none", borderRadius: 6, padding: "8px 14px", fontSize: 12, fontWeight: 800, cursor: "pointer", fontFamily: F, boxShadow: "0 6px 14px rgba(37, 99, 235, 0.18)" },
  userBadge: { background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 6, color: "#1d4ed8", padding: "7px 10px", fontSize: 12, fontWeight: 800 },
  cloudBadge: { background: "#ecfdf3", border: "1px solid #bbf7d0", borderRadius: 6, color: "#166534", padding: "7px 10px", fontSize: 11, fontWeight: 800 },
  tabOff: { background: "none", border: "none", color: "#667085", fontSize: 12, fontWeight: 600, padding: "9px 14px", cursor: "pointer", borderBottom: "2px solid transparent", fontFamily: F, whiteSpace: "nowrap" },
  tabOn: { background: "none", border: "none", color: "#172033", fontSize: 12, fontWeight: 800, padding: "9px 14px", cursor: "pointer", borderBottom: "2px solid #2563eb", fontFamily: F, whiteSpace: "nowrap" },
  body: { flex: 1, padding: 20, overflow: "auto" },
  fade: { animation: "fadeIn 0.3s ease" },
  fadeStack: { animation: "fadeIn 0.3s ease", display: "flex", flexDirection: "column", gap: 20 },
  fadeStackLg: { animation: "fadeIn 0.3s ease", display: "flex", flexDirection: "column", gap: 24 },
  heroRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 12 },
  h2: { margin: 0, fontSize: 22, fontWeight: 800, color: "#172033" },
  muted: { margin: "4px 0 0", fontSize: 13, color: "#667085" },
  statsRow: { display: "flex", gap: 16 },
  statLabel: { fontSize: 10, color: "#667085", textTransform: "uppercase", letterSpacing: 0.5 },
  secTitle: { fontSize: 12, fontWeight: 800, textTransform: "uppercase", letterSpacing: 0.6, margin: "0 0 10px" },
  count: { fontSize: 11, color: "#667085", fontWeight: 600, marginLeft: 4 },
  actionList: { display: "flex", flexDirection: "column", gap: 5 },
  actionCard: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: "12px 14px", gap: 10, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)" },
  actionCardEdit: { display: "flex", alignItems: "center", justifyContent: "space-between", background: "#ffffff", border: "1px solid #93c5fd", borderRadius: 8, padding: "12px 14px", gap: 10, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)", flexWrap: "wrap" },
  inlineEditGrid: { display: "flex", gap: 6, alignItems: "center", flex: 1, minWidth: 680, overflowX: "auto" },
  actionMain: { flex: 1, cursor: "pointer", display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  leadName: { color: "#172033", fontWeight: 800, fontSize: 13 },
  chips: { display: "flex", gap: 6, marginTop: 4, flexWrap: "wrap" },
  chip: { fontSize: 10, padding: "2px 7px", borderRadius: 4, background: "#eef2f7", color: "#475467", fontWeight: 600 },
  chipWarn: { fontSize: 10, padding: "2px 7px", borderRadius: 4, background: "#fef3c7", color: "#92400e", fontWeight: 700 },
  chipDanger: { fontSize: 10, padding: "2px 7px", borderRadius: 4, background: "#fee2e2", color: "#b91c1c", fontWeight: 700 },
  quickRow: { display: "flex", gap: 4, flexWrap: "wrap", justifyContent: "flex-end" },
  qBtn: { background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 5, color: "#344054", fontSize: 11, padding: "6px 8px", cursor: "pointer", fontFamily: F, display: "flex", alignItems: "center", gap: 4, whiteSpace: "nowrap" },
  qBtnSmall: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 4, fontSize: 11, cursor: "pointer", padding: "2px 5px", color: "#475467" },
  empty: { textAlign: "center", padding: 42, color: "#667085", background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)" },
  kanbanWrap: { display: "flex", flexDirection: "column", gap: 10, height: "100%", animation: "fadeIn 0.3s ease" },
  kanban: { display: "flex", gap: 10, flex: 1, minHeight: 0, overflow: "auto" },
  kCol: { flex: 1, minWidth: 190, background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: 10, display: "flex", flexDirection: "column", boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)" },
  kHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8, padding: "0 4px" },
  kHeadLeft: { display: "flex", alignItems: "center", gap: 5 },
  kTitle: { fontSize: 10, fontWeight: 800, color: "#475467", textTransform: "uppercase", letterSpacing: 0.5 },
  kBadge: { fontSize: 9, color: "#475467", background: "#eef2f7", borderRadius: 10, padding: "1px 6px", fontWeight: 700 },
  kAmt: { fontSize: 10, color: "#667085", fontFamily: FM },
  kCards: { display: "flex", flexDirection: "column", gap: 5, flex: 1, overflow: "auto" },
  card: { background: "#f8fafc", border: "1px solid #e5eaf0", borderRadius: 6, padding: "9px 10px", cursor: "pointer" },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 6 },
  cardName: { display: "flex", alignItems: "center", gap: 5, fontSize: 12, fontWeight: 700, color: "#172033" },
  cardAmount: { fontSize: 10, color: "#667085", fontFamily: FM },
  quickSmallRow: { display: "flex", gap: 3, marginTop: 4, justifyContent: "flex-end" },
  lostBar: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: "9px 14px", display: "flex", alignItems: "center", flexWrap: "wrap", gap: 6 },
  lostTitle: { fontSize: 10, color: "#b91c1c", fontWeight: 800, marginRight: 10 },
  lostChip: { fontSize: 10, color: "#475467", background: "#eef2f7", padding: "4px 10px", borderRadius: 4, cursor: "pointer" },
  listToolbar: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10, flexWrap: "wrap", marginBottom: 10 },
  listActions: { display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  pageSizeControl: { display: "flex", alignItems: "center", gap: 6, color: "#475467", fontSize: 12, fontWeight: 700 },
  pageSizeSelect: { background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 6, color: "#172033", padding: "7px 8px", fontSize: 12, fontFamily: F },
  selectionBar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, flexWrap: "wrap", background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: "8px 8px 0 0", padding: "8px 12px", color: "#475467", fontSize: 12, fontWeight: 700 },
  pager: { display: "flex", alignItems: "center", gap: 8, color: "#667085", fontSize: 11 },
  filterBar: { display: "flex", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  fOff: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 5, color: "#475467", fontSize: 10, padding: "5px 10px", cursor: "pointer", fontFamily: F, display: "flex", alignItems: "center", gap: 4 },
  fOn: { background: "#eff6ff", border: "1px solid #93c5fd", borderRadius: 5, color: "#1d4ed8", fontSize: 10, padding: "5px 10px", cursor: "pointer", fontFamily: F, display: "flex", alignItems: "center", gap: 4, fontWeight: 800 },
  divider: { width: 1, background: "#dbe5f0", margin: "0 4px" },
  tHead: { display: "flex", padding: "8px 14px", background: "#eef2f7", fontSize: 9, color: "#475467", textTransform: "uppercase", letterSpacing: 0.5, fontWeight: 800, minWidth: 760, borderRadius: "8px 8px 0 0" },
  tRow: { display: "flex", padding: "11px 14px", borderBottom: "1px solid #e5eaf0", cursor: "pointer", fontSize: 12, alignItems: "center", minWidth: 760, background: "#ffffff" },
  tRowEdit: { display: "flex", gap: 6, padding: "7px 10px", borderBottom: "1px solid #e5eaf0", fontSize: 12, alignItems: "center", minWidth: 900, background: "#ffffff", overflowX: "auto" },
  gridInput: { flex: 1, minWidth: 115, background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 5, color: "#172033", padding: "7px 8px", fontSize: 11, fontFamily: F, outline: "none" },
  tableMuted: { flex: 1, color: "#667085" },
  noResults: { textAlign: "center", color: "#667085", padding: 20, fontSize: 13 },
  calendarWrap: { animation: "fadeIn 0.3s ease", display: "flex", flexDirection: "column", gap: 14 },
  calendarHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: 12 },
  calendarControls: { display: "flex", gap: 8, flexWrap: "wrap" },
  calendarLayout: { display: "grid", gridTemplateColumns: "minmax(0, 1.6fr) minmax(280px, 0.8fr)", gap: 14, alignItems: "start" },
  calendarPanel: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: 14, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)", overflowX: "auto" },
  calendarTitle: { textTransform: "capitalize", fontSize: 15, fontWeight: 800, color: "#172033", marginBottom: 12 },
  weekGrid: { display: "grid", gridTemplateColumns: "repeat(7, minmax(82px, 1fr))", gap: 6, minWidth: 640 },
  weekday: { fontSize: 10, color: "#667085", fontWeight: 800, textTransform: "uppercase", letterSpacing: 0.5, padding: "0 6px 4px" },
  monthGrid: { display: "grid", gridTemplateColumns: "repeat(7, minmax(82px, 1fr))", gap: 6, minWidth: 640 },
  dayCell: { minHeight: 92, background: "#f8fafc", border: "1px solid #e5eaf0", borderRadius: 6, padding: 8, cursor: "pointer", fontFamily: F, textAlign: "left", display: "flex", flexDirection: "column", gap: 5, color: "#172033" },
  dayMuted: { opacity: 0.42 },
  daySelected: { borderColor: "#2563eb", background: "#eff6ff", boxShadow: "0 0 0 2px #2563eb18" },
  dayToday: { borderColor: "#93c5fd" },
  dayNumber: { fontSize: 12, fontWeight: 800, lineHeight: 1 },
  dayCount: { alignSelf: "flex-start", fontSize: 10, color: "#1d4ed8", background: "#dbeafe", borderRadius: 999, padding: "2px 7px", fontWeight: 800 },
  dayDots: { display: "flex", gap: 3, marginTop: "auto" },
  dayDot: { width: 7, height: 7, borderRadius: "50%" },
  calendarSide: { display: "flex", flexDirection: "column", gap: 12, minWidth: 0 },
  calendarList: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: 12, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)" },
  calendarItem: { display: "flex", justifyContent: "space-between", gap: 10, alignItems: "center", padding: "10px 0", borderBottom: "1px solid #eef2f7" },
  calendarItemMain: { cursor: "pointer", minWidth: 0, display: "flex", flexDirection: "column", gap: 5, flex: 1 },
  pill: { fontSize: 9, padding: "2px 7px", borderRadius: 4, fontWeight: 700 },
  bigStatsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10 },
  bigStat: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: "15px 18px", display: "flex", flexDirection: "column", gap: 3, boxShadow: "0 1px 3px rgba(15, 23, 42, 0.04)" },
  bigStatLabel: { fontSize: 10, color: "#667085", textTransform: "uppercase", letterSpacing: 0.8 },
  bigStatValue: { fontSize: 26, fontWeight: 700, fontFamily: FM, lineHeight: 1.1 },
  bigStatSub: { fontSize: 11, color: "#667085" },
  funnelRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 6 },
  funnelLabel: { width: 82, fontSize: 11, color: "#475467", textAlign: "right" },
  funnelTrack: { flex: 1, background: "#eef2f7", borderRadius: 4, height: 26, overflow: "hidden" },
  funnelFill: { height: "100%", borderRadius: 4, display: "flex", alignItems: "center", paddingLeft: 8, transition: "width 0.4s" },
  funnelCount: { fontSize: 11, fontWeight: 700, color: "#fff", fontFamily: FM },
  funnelAmt: { fontSize: 10, color: "#667085", width: 55, textAlign: "right", fontFamily: FM },
  twoCols: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  metricRow: { display: "flex", justifyContent: "space-between", padding: "6px 0", borderBottom: "1px solid #dbe5f0" },
  metricName: { fontSize: 12, color: "#475467" },
  metricCount: { fontSize: 12, fontWeight: 700, fontFamily: FM },
  noData: { color: "#667085", fontSize: 12 },
  backBtn: { background: "none", border: "none", color: "#2563eb", fontSize: 12, cursor: "pointer", padding: 0, marginBottom: 14, fontFamily: F, fontWeight: 800 },
  detailHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12 },
  titleRow: { display: "flex", alignItems: "center", gap: 8 },
  detailActions: { display: "flex", gap: 6, flexWrap: "wrap", justifyContent: "flex-end" },
  stageRow: { display: "flex", gap: 4, margin: "16px 0 8px", flexWrap: "wrap" },
  stgBtn: { background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 5, color: "#475467", fontSize: 10, padding: "6px 10px", cursor: "pointer", fontFamily: F, fontWeight: 700 },
  followBar: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap", marginBottom: 14 },
  followLabel: { fontSize: 11, color: "#667085", fontWeight: 800, textTransform: "uppercase" },
  followDate: { fontSize: 11, color: "#475467", fontFamily: FM },
  followDanger: { fontSize: 11, color: "#b91c1c", fontFamily: FM, fontWeight: 800 },
  lossNote: { background: "#ef444412", border: "1px solid #ef444433", borderRadius: 6, padding: "8px 12px", marginBottom: 12, fontSize: 12, color: "#f87171" },
  editBox: { marginTop: 12 },
  infoWrap: { marginTop: 16 },
  infoGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))", gap: 14, marginBottom: 14 },
  infoLabel: { fontSize: 10, color: "#667085", textTransform: "uppercase", letterSpacing: 0.5 },
  infoValue: { fontSize: 13, margin: "2px 0 0" },
  notes: { fontSize: 13, color: "#475467", background: "#ffffff", border: "1px solid #dbe5f0", padding: 12, borderRadius: 6, lineHeight: 1.5, margin: 0 },
  history: { marginTop: 24 },
  tlItem: { display: "flex", gap: 10, padding: "7px 0", borderLeft: "2px solid #dbe5f0", marginLeft: 7, paddingLeft: 14, position: "relative" },
  tlDot: { position: "absolute", left: -5, top: 12, width: 7, height: 7, borderRadius: "50%", background: "#2563eb" },
  tlHead: { display: "flex", justifyContent: "space-between", gap: 12 },
  tlType: { fontSize: 10, fontWeight: 800, color: "#1d4ed8", textTransform: "uppercase" },
  tlDate: { fontSize: 10, color: "#667085" },
  tlNote: { fontSize: 12, color: "#475467", margin: "3px 0 0", lineHeight: 1.4 },
  buttonRow: { display: "flex", gap: 8, marginTop: 12 },
  confirmBox: { display: "flex", gap: 10, alignItems: "center", marginTop: 10, padding: 10, background: "#ef444412", borderRadius: 6 },
  overlay: { position: "fixed", inset: 0, background: "rgba(15, 23, 42, 0.42)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 16 },
  modal: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 8, padding: 22, width: "100%", maxWidth: 500, maxHeight: "86vh", overflow: "auto", boxShadow: "0 20px 55px rgba(15, 23, 42, 0.18)" },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 14 },
  mTitle: { fontSize: 15, fontWeight: 800, color: "#172033", margin: 0 },
  segment: { display: "flex", background: "#eef2f7", border: "1px solid #dbe5f0", borderRadius: 6, overflow: "hidden" },
  segOn: { background: "#2563eb", color: "#ffffff", border: "none", padding: "7px 11px", fontSize: 11, fontFamily: F, cursor: "pointer", fontWeight: 800 },
  segOff: { background: "transparent", color: "#475467", border: "none", padding: "7px 11px", fontSize: 11, fontFamily: F, cursor: "pointer", fontWeight: 700 },
  help: { fontSize: 12, color: "#667085", margin: "0 0 12px", lineHeight: 1.45 },
  modalActions: { display: "flex", gap: 8, marginTop: 14, justifyContent: "flex-end" },
  presetRow: { display: "flex", gap: 6, marginBottom: 8, flexWrap: "wrap" },
  lossList: { display: "flex", flexDirection: "column", gap: 6 },
  lossOpt: { background: "#ffffff", border: "1px solid #dbe5f0", borderRadius: 6, padding: "9px 14px", fontSize: 12, color: "#475467", cursor: "pointer", textAlign: "left", fontFamily: F },
  priBtn: { background: "#2563eb", color: "#fff", border: "none", borderRadius: 6, padding: "8px 14px", fontSize: 12, fontWeight: 800, cursor: "pointer", fontFamily: F, boxShadow: "0 6px 14px rgba(37, 99, 235, 0.16)" },
  secBtn: { background: "#ffffff", color: "#344054", border: "1px solid #cbd5e1", borderRadius: 6, padding: "8px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: F },
  danBtn: { background: "#f8717118", color: "#f87171", border: "1px solid #f8717133", borderRadius: 6, padding: "8px 14px", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: F },
  lbl: { fontSize: 9, color: "#667085", textTransform: "uppercase", letterSpacing: 0.5, display: "block", marginBottom: 4, fontWeight: 800 },
  input: { width: "100%", background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 6, color: "#172033", padding: "9px 11px", fontSize: 12, fontFamily: F, outline: "none", boxSizing: "border-box" },
  uploadBox: { display: "flex", flexDirection: "column", gap: 4, border: "1px dashed #93c5fd", background: "#eff6ff", borderRadius: 8, padding: 14, marginBottom: 10, cursor: "pointer" },
  imagePreview: { width: "100%", maxHeight: 180, objectFit: "contain", border: "1px solid #dbe5f0", borderRadius: 8, marginBottom: 10, background: "#f8fafc" },
  ocrStatus: { fontSize: 12, color: "#1d4ed8", background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 6, padding: "8px 10px", margin: "0 0 10px" },
  importReview: { display: "flex", flexDirection: "column", gap: 10, marginTop: 10 },
  importSummary: { display: "flex", gap: 6, flexWrap: "wrap" },
  readyBadge: { fontSize: 10, color: "#166534", background: "#dcfce7", border: "1px solid #bbf7d0", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  reviewBadge: { fontSize: 10, color: "#92400e", background: "#fef3c7", border: "1px solid #fde68a", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  invalidBadge: { fontSize: 10, color: "#991b1b", background: "#fee2e2", border: "1px solid #fecaca", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  importTitle: { fontSize: 10, color: "#667085", textTransform: "uppercase", letterSpacing: 0.5, margin: "2px 0 6px", fontWeight: 800 },
  importRow: { display: "flex", justifyContent: "space-between", gap: 10, alignItems: "center", background: "#f8fafc", border: "1px solid #e5eaf0", borderRadius: 6, padding: "8px 10px", fontSize: 12 },
  importEditRow: { display: "flex", gap: 6, alignItems: "center", background: "#f8fafc", border: "1px solid #e5eaf0", borderRadius: 6, padding: 8, marginBottom: 6, fontSize: 12, overflowX: "auto" },
  importInput: { flex: 1, minWidth: 118, background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: 5, color: "#172033", padding: "7px 8px", fontSize: 11, fontFamily: F, outline: "none" },
  importMeta: { fontSize: 11, color: "#667085", marginTop: 2 },
  priorityHigh: { fontSize: 10, color: "#166534", background: "#dcfce7", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  priorityMid: { fontSize: 10, color: "#1d4ed8", background: "#dbeafe", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  priorityLow: { fontSize: 10, color: "#667085", background: "#eef2f7", borderRadius: 999, padding: "3px 8px", fontWeight: 800 },
  fRow: { display: "flex", gap: 8 },
};
